---------------->>>> SUPERCLUSTER INSTANCES ONLY <<<<---------------------
--
-- SBC_DIR_LIST_DETAILS  (Table)
--
CREATE GLOBAL TEMPORARY TABLE SBC.SBC_DIR_LIST_DETAILS
(
  FILENAME                VARCHAR2(255 BYTE),
  FILE_SIZE_IN_BYTES      varchar2(255),
  FILE_DATE_LAST_MODIFIED date
)
ON COMMIT PRESERVE ROWS
RESULT_CACHE (MODE DEFAULT)
NOCACHE;

GRANT ALL ON SBC.SBC_DIR_LIST_DETAILS TO APPS with grant option;

-- as apps
CREATE OR REPLACE SYNONYM APPS.SBC_DIR_LIST_DETAILS FOR SBC.SBC_DIR_LIST_DETAILS;



---------------->>>> vader ONLY <<<<---------------------
CREATE GLOBAL TEMPORARY TABLE SBC.SBC_DIR_LIST_DETAILS
(
  FILENAME                VARCHAR2(255 BYTE),
  FILE_SIZE_IN_BYTES      varchar2(255),
  FILE_DATE_LAST_MODIFIED date
)
ON COMMIT PRESERVE ROWS
NOCACHE;

GRANT ALL ON SBC.SBC_DIR_LIST_DETAILS TO APPS with grant option;

-- as apps
CREATE OR REPLACE SYNONYM APPS.SBC_DIR_LIST_DETAILS FOR SBC.SBC_DIR_LIST_DETAILS;
